### ISSUE TITLE
Better PER by Mirco Rivanelli et al

### ISSUE THREAD

**Issue by sdrobert** [OrcusCZ/NNAcousticModeling#1]
Hi there,

Great (and thorough) work. Just wanted to point out that Mirco Rivanelli et al report better average PERs than the 15.58%. You can find their repository here: https://github.com/mravanelli/pytorch-kaldi.

Best,
Sean

**Comment by vanekyj** [comment]
Hi Sean,
Thanks for the post. We found the Ravanelli's paper later and add the reference to our next papers at SPECOM 2018 and SLSP 2018.
