### ISSUE TITLE
Targets for test?

### ISSUE THREAD

**Issue by souryadey** [OrcusCZ/NNAcousticModeling#2]
Hi, a couple of questions:
1) I was reading your paper "A Survey of Recent DNN Architectures on the TIMIT Phone Recognition Task" and want to know how you got the test PER metrics. Why are there are no targets for test data?
2) My estimate is that you used 50 speakers for the development set. What was the criteria for selecting them?

**Comment by vanekyj** [comment]
Firsts, thanks for questions.

The TIMIT corpus has predefined standard train/dev/test lists. So, all published papers should be compatible. The lists are in the data directory.
Dev and test targets (39 phones alphabet) are recog/dev_ref.mlf and recog/test_ref.mlf.
The PER evaluation is done by scripts/util/levenstein.py. It is a reimplementation of the NIST "official" evaluation perl script, that is included in Kaldi. Therefore, evaluation should be the same in the papers also.

**Comment by souryadey** [comment]
Thank you for the clarifications.
